DROP TABLE IF EXISTS chats;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE chats (
    chat_id SERIAL PRIMARY KEY,
    user_id_1 INT NOT NULL,
    user_id_2 INT NOT NULL,
    message TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);