name: mqchat

services: 
  db: 
    image: postgres
    # restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    
  # server:
  #   build: ./server
  #   restart: always
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - db
  #     - auth_service
  #     - chat_service
  #     - user_service
  #     - connection_service
  #     - mqtt_service
  #   environment:
  #     DEBUG: "True"
    
  # auth_service:
  #   build: ./services/auth/
  #   restart: always
  #   ports:
  #     - "8001:8001"
  #   depends_on:
  #     - db
  #   environment:
  #     DEBUG: "True"
  #     ALLOWED_HOSTS: "*"

  chat_service:
    build: 
      context: .
      dockerfile: services/chat/Dockerfile
    image: chat
    restart: always
    ports:
      - "2200:8002"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DEBUG: "True"

  user_service:
    build:
      context: .
      dockerfile: services/user/Dockerfile
    image: user
    restart: always
    ports:
      - "2000:8003"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DEBUG: "True"

  # connection_service:
  #   build: ./connection_service
  #   restart: always
  #   ports:
  #     - "8004:8004"
  #   depends_on:
  #     - db
  #   environment:
  #     DEBUG: "True"

  # mqtt_service:
  #   build: ./mqtt_service
  #   restart: always
  #   ports:
  #     - "1883:1883"
  #   depends_on:
  #     - db
  #   environment:
  #     DEBUG: "True"
      
  


 