name: mqchat

services: 
  db: 
    image: postgres
    # restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    
  server:
    build: 
      context: .
      dockerfile: api/Dockerfile 
    ports:
      - "8000:8000"
      - "8001:8001"
    depends_on:
      db:
        condition: service_healthy
  
    environment:
      DEBUG: "True"


  chat_service:
    build: 
      context: .
      dockerfile: services/chat/Dockerfile
    image: chat
    restart: always
    ports:
      - "2200:8002"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DEBUG: "True"

  user_service:
    build:
      context: .
      dockerfile: services/user/Dockerfile
    image: user
    restart: always
    ports:
      - "2000:8003"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DEBUG: "True"

  room_service:
    build: 
      context: .
      dockerfile: services/rooms/Dockerfile
    restart: always
    ports:
      - "2100:8004"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DEBUG: "True"

 
      
  


 