wipe = true
output = "gen/models"
no-tests = true
add-enum-types = true


[psql]
 dbname = "postgres"
 user = "postgres"
 host = "localhost"
 port = 5432
 pass = "postgres"
 sslmode = "disable"
 blacklist = ["other"]
