wipe = true
output = "models"
no-tests = true
add-enum-types = true


[psql]
 dbname = "mqdb"
 user = "mqdbUser"
 host = "localhost"
 port = "5432"
 sslmode = "disable"
 blacklist = ["migrations","other"]
